import { FriendUser, SocialFeedActivity } from '../types';

export const INITIAL_FRIENDS: FriendUser[] = [
  {
    id: 'friend-1',
    name: 'Alex Chen',
    username: '@alex_runner',
    email: 'alex.chen@gmail.com',
    avatar: '🏃‍♂️',
    bio: 'Marathon trainee & consistency enthusiast. Never skip day one!',
    plantStage: '🌳 Grand Oak (Lvl 5)',
    currentStreak: 21,
    totalCompletions: 142,
    isFriend: true,
    requestStatus: 'accepted',
    habits: [
      {
        id: 'fh-101',
        name: 'Morning 5km Run',
        description: 'Brisk cardio run every morning at dawn.',
        icon: 'Activity',
        color: '#FF6B6B',
        frequency_type: 'daily',
        scheduled_days: [0, 1, 2, 3, 4, 5, 6],
        reminder_time: '06:00',
        currentStreak: 21,
        isCompletedToday: true,
        adoptersCount: 48,
      },
      {
        id: 'fh-102',
        name: 'Hydrate 3L Water',
        description: 'Drink 3 liters of fresh water spread across the day.',
        icon: 'Droplets',
        color: '#38BDF8',
        frequency_type: 'daily',
        scheduled_days: [0, 1, 2, 3, 4, 5, 6],
        reminder_time: '09:00',
        currentStreak: 35,
        isCompletedToday: true,
        adoptersCount: 112,
      },
      {
        id: 'fh-103',
        name: 'Read 20 Pages',
        description: 'Read self-improvement and non-fiction books.',
        icon: 'BookOpen',
        color: '#F59E0B',
        frequency_type: 'daily',
        scheduled_days: [0, 1, 2, 3, 4, 5, 6],
        reminder_time: '21:30',
        currentStreak: 14,
        isCompletedToday: false,
        adoptersCount: 76,
      },
    ],
  },
  {
    id: 'friend-2',
    name: 'Maya Lin',
    username: '@maya_zen',
    email: 'maya.lin@gmail.com',
    avatar: '🧘‍♀️',
    bio: 'Mindfulness practitioner, yogi & plant parent 🌿',
    plantStage: '🌺 Blooming Shrub (Lvl 4)',
    currentStreak: 16,
    totalCompletions: 98,
    isFriend: true,
    requestStatus: 'accepted',
    habits: [
      {
        id: 'fh-201',
        name: 'Deep Meditation',
        description: '15 minutes of mindful breathwork and calm focus.',
        icon: 'Sparkles',
        color: '#7C5CFF',
        frequency_type: 'daily',
        scheduled_days: [0, 1, 2, 3, 4, 5, 6],
        reminder_time: '07:00',
        currentStreak: 16,
        isCompletedToday: true,
        adoptersCount: 89,
      },
      {
        id: 'fh-202',
        name: 'Evening Stretch & Yoga',
        description: 'Full body unwinding and gentle flexibility flow.',
        icon: 'Heart',
        color: '#EC4899',
        frequency_type: 'daily',
        scheduled_days: [0, 1, 2, 3, 4, 5, 6],
        reminder_time: '20:00',
        currentStreak: 19,
        isCompletedToday: false,
        adoptersCount: 64,
      },
    ],
  },
  {
    id: 'friend-3',
    name: 'Rahul Sharma',
    username: '@rahul_dev',
    email: 'rahul.sharma@gmail.com',
    avatar: '💻',
    bio: 'Software engineer building habits one commit at a time 🚀',
    plantStage: '🌱 Thriving Bush (Lvl 3)',
    currentStreak: 12,
    totalCompletions: 67,
    isFriend: true,
    requestStatus: 'accepted',
    habits: [
      {
        id: 'fh-301',
        name: 'LeetCode Problem',
        description: 'Solve 1 algorithmic or system design challenge daily.',
        icon: 'Cpu',
        color: '#10B981',
        frequency_type: 'daily',
        scheduled_days: [0, 1, 2, 3, 4, 5, 6],
        reminder_time: '08:30',
        currentStreak: 12,
        isCompletedToday: true,
        adoptersCount: 135,
      },
      {
        id: 'fh-302',
        name: 'No Phone Before Bed',
        description: 'Put screens away 45 minutes before sleeping.',
        icon: 'Moon',
        color: '#6366F1',
        frequency_type: 'daily',
        scheduled_days: [0, 1, 2, 3, 4, 5, 6],
        reminder_time: '22:15',
        currentStreak: 9,
        isCompletedToday: false,
        adoptersCount: 92,
      },
    ],
  },
  {
    id: 'friend-4',
    name: 'Sarah Jenkins',
    username: '@sarah_fit',
    email: 'sarah.j@gmail.com',
    avatar: '🥗',
    bio: 'Nutritionist & strength coach. Daily small wins compound! 💪',
    plantStage: '🌿 Young Sapling (Lvl 2)',
    currentStreak: 8,
    totalCompletions: 45,
    isFriend: false,
    requestStatus: 'none',
    habits: [
      {
        id: 'fh-401',
        name: 'Zero Refined Sugar',
        description: 'Whole foods only. Replace sweets with berries & fruit.',
        icon: 'Apple',
        color: '#14B8A6',
        frequency_type: 'daily',
        scheduled_days: [0, 1, 2, 3, 4, 5, 6],
        reminder_time: '12:00',
        currentStreak: 8,
        isCompletedToday: true,
        adoptersCount: 154,
      },
      {
        id: 'fh-402',
        name: 'Strength Workout',
        description: '45-minute compound lifts or bodyweight training.',
        icon: 'Dumbbell',
        color: '#EF4444',
        frequency_type: 'daily',
        scheduled_days: [0, 2, 4, 6],
        reminder_time: '17:30',
        currentStreak: 15,
        isCompletedToday: true,
        adoptersCount: 88,
      },
    ],
  },
  {
    id: 'friend-5',
    name: 'David Kim',
    username: '@david_focus',
    email: 'david.kim@gmail.com',
    avatar: '🎯',
    bio: 'Product manager focusing on deep work blocks & mental clarity.',
    plantStage: '🌲 Ancient Redwood (Lvl 6)',
    currentStreak: 28,
    totalCompletions: 210,
    isFriend: false,
    requestStatus: 'none',
    habits: [
      {
        id: 'fh-501',
        name: 'Deep Work 90m Block',
        description: 'Zero distractions, full focus session on hardest project.',
        icon: 'Target',
        color: '#F97316',
        frequency_type: 'daily',
        scheduled_days: [0, 1, 2, 3, 4],
        reminder_time: '09:00',
        currentStreak: 28,
        isCompletedToday: true,
        adoptersCount: 180,
      },
      {
        id: 'fh-502',
        name: 'Gratitude Journaling',
        description: 'Write down 3 specific things I am grateful for today.',
        icon: 'Edit3',
        color: '#A855F7',
        frequency_type: 'daily',
        scheduled_days: [0, 1, 2, 3, 4, 5, 6],
        reminder_time: '21:00',
        currentStreak: 30,
        isCompletedToday: true,
        adoptersCount: 71,
      },
    ],
  },
];

export const INITIAL_FEED: SocialFeedActivity[] = [
  {
    id: 'feed-1',
    friendId: 'friend-1',
    friendName: 'Alex Chen',
    friendUsername: '@alex_runner',
    friendAvatar: '🏃‍♂️',
    habitName: 'Morning 5km Run',
    habitIcon: 'Activity',
    habitColor: '#FF6B6B',
    type: 'streak_milestone',
    streakCount: 21,
    timestamp: '12m ago',
    kudosCount: 7,
    hasGivenKudos: false,
  },
  {
    id: 'feed-2',
    friendId: 'friend-2',
    friendName: 'Maya Lin',
    friendUsername: '@maya_zen',
    friendAvatar: '🧘‍♀️',
    habitName: 'Deep Meditation',
    habitIcon: 'Sparkles',
    habitColor: '#7C5CFF',
    type: 'completed',
    timestamp: '35m ago',
    kudosCount: 4,
    hasGivenKudos: true,
  },
  {
    id: 'feed-3',
    friendId: 'friend-3',
    friendName: 'Rahul Sharma',
    friendUsername: '@rahul_dev',
    friendAvatar: '💻',
    habitName: 'LeetCode Problem',
    habitIcon: 'Cpu',
    habitColor: '#10B981',
    type: 'completed',
    timestamp: '1h ago',
    kudosCount: 9,
    hasGivenKudos: false,
  },
  {
    id: 'feed-4',
    friendId: 'friend-1',
    friendName: 'Alex Chen',
    friendUsername: '@alex_runner',
    friendAvatar: '🏃‍♂️',
    habitName: 'Hydrate 3L Water',
    habitIcon: 'Droplets',
    habitColor: '#38BDF8',
    type: 'completed',
    timestamp: '2h ago',
    kudosCount: 3,
    hasGivenKudos: false,
  },
];
